<?php

namespace AppBundle\Repository;

/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAssetByCodeLike($code){
        $result = $this->createQueryBuilder('a')
					   ->where('a.code LIKE :code')
					   ->setParameter('code', $code . "%")
					   ->getQuery()
					   ->getResult();
		return $result;
	}

	public function findAssetsWithoutUser(){
	
		$query = $this->getEntityManager()
            ->createQuery(
                'SELECT a , COUNT(u) AS userCount
                 FROM AppBundle:Asset a
				 LEFT JOIN a.users u
				 GROUP BY a.id
				 HAVING userCount = 0
				');

		return $query->getResult();
	}
}
