<?php

namespace AppBundle\Repository;

/**
 * MaintenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintenanceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByScheduleGreaterThanWithLimit(\DateTime $dateTime, int $count){
	
		$query = $this->createQueryBuilder('m')
		    ->where('m.schedule > :dateTime')
		    ->setParameter('dateTime', $dateTime)
		    ->orderBy('m.schedule', 'ASC')
		    ->setMaxResults($count)
		    ->getQuery();

		$schedules = $query->getResult();
}


}
