<?php

namespace AppBundle\Repository;

/**
 * MaintenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintenanceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByScheduleGreaterThanWithLimit(\DateTime $dateTime, int $count){
	
		$query = $this->getEntityManager()
            ->createQuery(
                'SELECT m 
                 FROM AppBundle:Maintenance m 
                 WHERE m.schedule >= :dateTime 
                 ORDER BY m.schedule ASC
                 '
            )
		    //->where('m.schedule > :dateTime')
		    ->setParameter('dateTime', $dateTime)
		    //->orderBy('m.schedule', 'ASC')
		    //->setMaxResults($count)
		    ;

		return $query->getResult();
}


}
